version: "3"

services:
  core:
    container_name: landingpage
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - landingpage_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  landingpage_network:
